[versions]
kotlin = "1.6.21"
ktor = "2.0.1"

[libraries]
ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor"}
ktor-client-curl = { group = "io.ktor", name = "ktor-client-curl", version.ref = "ktor"}

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
